name: client
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  image:
  jaguar_resty:
  vector_math:
  jaguar_serializer:
  ezwebgl:
    path: ../ezwebgl
  spec:
    path: ../spec
  loader:
    path: ../loader
  pathing:
    path: ../pathing
  pos:
    path: ../pos
  meta:

dev_dependencies:
  build_runner:
  build_web_compilers:
  jaguar_serializer_cli:
