name: loader
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: seragud <email@example.com>

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  image:
  spec:
    path: ../spec
  ezwebgl:
    path: ../ezwebgl
  yaml:

dev_dependencies:
  build_runner:
  build_web_compilers:
